### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by jiaaihhy** [ChristophReich1996/MaxViT#1]
Hello dear, Thanks for your reproducing this paper, and I want to do this model too.In your code, I find that grid operation seems some problem .I think that your operation refers to block operation rather than global grid operator. How to do global grid operator? And Im waiting for your continuous releasing the code. Thank you.

**Comment by ChristophReich1996** [comment]
Hi @jiaaihhy, 

Thanks for your interest. Yes, you are correct, the naming was flipped, should be fixed now. I think the global grid partition can be implemented by using the [`unfold`](https://pytorch.org/docs/stable/generated/torch.Tensor.unfold.html) function of PyTorch. 

PS: Feel free to open a pull request in case you want to add or change something in the current implementation, I think I should have a first running version ready in the next few days :)

Cheers Christoph
