### ISSUE TITLE
how to get The pytorch version pretained weight checkpoint

### ISSUE THREAD

**Issue by mywebinfo65536** [ChristophReich1996/MaxViT#11]
Hi good job!  I have a question that How can I convert the TF version pretained weight checkpoint file to pytorch version ?

**Comment by PangXuejiao** [comment]
Hello, have you solved the problem? I had the same problem.

**Comment by mywebinfo65536** [comment]
Not yet.  Hope the paper's author release it.

**Comment by ChristophReich1996** [comment]
Hi, the [timm](https://github.com/rwightman/pytorch-image-models) library offers pre-trained weights on ImageNet. Highly recommend checking timm out!
