### ISSUE TITLE
error: RuntimeError: Tensor for argument #2 'weight' is on CPU, but expected it to be on GPU (while checking arguments for cudnn_batch_norm)

### ISSUE THREAD

**Issue by Geek-lixiang** [ChristophReich1996/MaxViT#4]
Thank you for your work.
I import the model, and push it to gpu, but the error happen:
RuntimeError: Tensor for argument #2 'weight' is on CPU, but expected it to be on GPU (while checking arguments for cudnn_batch_norm)
Lookiing forward for your reply!

**Comment by MeteorsHub** [comment]
Same thing happens to me

**Comment by SNeugber** [comment]
Same issue, has anyone found a solution? I can't see anything obvious..

**Comment by LvGuangzu** [comment]
同样的问题，我将MaxVit的network放到gpu上，但是他在过程中报错我的weight在cpu上

**Comment by LvGuangzu** [comment]
> 谢谢你的工作。我导入模型，并将其推送到GPU，但错误发生了：运行时错误：参数#2的张量“权重”在CPU上，但期望它在GPU上（同时检查参数cudnn_batch_norm）期待您的回复！

Have you solved this problem?

**Comment by LvGuangzu** [comment]
I tried to run the model from the GPU, but he told me there was weight on the CPU in the middle

**Comment by vztu** [comment]
Please refer to timm's implementation: https://github.com/rwightman/pytorch-image-models 

also https://github.com/ChristophReich1996/MaxViT/issues/9

**Comment by LvGuangzu** [comment]
> I tried to run the model from the GPU, but he told me there was weight on the CPU in the middle

have solved

**Comment by MichaelHealy99** [comment]
> > I tried to run the model from the GPU, but he told me there was weight on the CPU in the middle
> 
> have solved

Hey, can you say how you solved this? Thank you!

**Comment by mywebinfo65536** [comment]
Hi, I have fixed it by this way:   you can add this line:  self.blocks.cuda()  in the __init__() of the MaxViTStage class to have a try.

**Comment by ChristophReich1996** [comment]
Hi everyone, sorry for my very late response! **The bug is now fixed**. Please note [timm](https://github.com/rwightman/pytorch-image-models) as always got a probably even better implementation and pre-trained weights! Highly recommend checking timm out.
