### ISSUE TITLE
extract features 

### ISSUE THREAD

**Issue by mathshangw** [ChristophReich1996/MaxViT#5]

**Comment by ChristophReich1996** [comment]
Hi @mathshangw,

Sorry for my very late response. You can extract the last feature map by calling the `forward_features` method. If you need to access other feature maps, I would suggest writing your own custom forward pass. Another solution would maybe to use the [feature extraction package](https://pytorch.org/vision/stable/feature_extraction.html) of Torchvision.

Cheers,
Christoph
