### ISSUE TITLE
Grid Partition

### ISSUE THREAD

**Issue by DDxk369** [ChristophReich1996/MaxViT#6]
Thanks to the authors for sharing Maxvit open source, I really enjoyed this project and studied it for a few days. However, I didn't understand this part of the work on the Grid Partition. In my opinion, it looks almost the same as SWIN V1, so how does it accomplish the grid operation shown below? Looking forward to your advice, thank you
![image](https://user-images.githubusercontent.com/67983455/187826856-45f80185-5046-4a60-a1b7-40842b0e7881.png)

**Comment by ChristophReich1996** [comment]
Hi @DDxk369,

The grid partition is somewhat similar to the application of a strided convolution. Attention is not performed within directly neighboring pixels but inside a strided window. For more details, I would refer to section 3.2 (Multi-axis Attention) of the [original paper](https://arxiv.org/pdf/2204.01697.pdf) or [this function](https://github.com/ChristophReich1996/MaxViT/blob/b2757066821df0435ce780840f2c4c64a9ca19c1/maxvit/maxvit.py#L160). Regarding the similarity to the Swin Transformer approach, MaxViT uses a strided window, whereas Swin uses a shifted window approach in conjunction to the standard window attention (also utilized by MaxViT).

Cheers,
Christoph
