### ISSUE TITLE
a questione about the code in maxvit.py

### ISSUE THREAD

**Issue by YaoShunyu19** [ChristophReich1996/MaxViT#8]
hi!
I have a question about the line 400 in maxvit.py.
there is a skip-connection in block attention and grid attention, so may be we should use 'output = output + self.drop_path(self.mlp(self.norm_2(output)))', rather than '*'
Looking forward to your reply, thanks!

**Comment by ChristophReich1996** [comment]
Hi @HITYSY19,

Ohh yees, that is a severe bug. Thanks for pointing this out!

Cheers,
Christoph

**Comment by ChristophReich1996** [comment]
Fixed :)
