### ISSUE TITLE
Put the code on the GPU and run, but the run reports an error

### ISSUE THREAD

**Issue by LvGuangzu** [ChristophReich1996/MaxViT#9]
In this line of code
output = self.main_path(input)：line 69, in forward
Error
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking arugment for argument weight in method wrapper_cudnn_batch_norm)

**Comment by mywebinfo65536** [comment]
Hi, I have fixed it by this way:   you can add this line:  self.blocks.cuda()  in the __init__() of the MaxViTStage class to have a try.

**Comment by PangXuejiao** [comment]
> 

thank you very much!!!

**Comment by ChristophReich1996** [comment]
Just fixed, sorry for my late response!
